//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define IDB_BACKGROUND                  164
#define IDB_LOGO                        166
#define IDB_FROG_STAND                  168
#define IDB_FROG_DOWN                   170
#define IDB_FROG_DOWN_RIGHT             170
#define IDB_FROG_STAND_RIGHT            171
#define IDB_FROG_GO_RIGHT               172
#define IDB_FROG_GO_LEFT                173
#define IDB_FROG_STAND_LEFT             176
#define IDB_FROG_GO_LEFT2               178
#define IDB_FROG_GO_LEFT3               179
#define IDB_FROG_GO_LEFT1               182
#define IDB_FROG_GO_RIGHT1              183
#define IDB_FROG_GO_RIGHT2              184
#define IDB_FROG_JUMP_LEFT              185
#define IDB_BITMAP1                     187
#define IDB_FROG_JUMP_RIGHT             187
#define IDB_MONSTER_STAND_LEFT          189
#define IDB_MONSTER_STAND_RIGHT         190
#define IDB_EXIT1                       191
#define IDB_EXIT2                       192
#define IDB_START1                      193
#define IDB_BITMAP5                     194
#define IDB_START2                      194
#define IDB_FROG_ATTACK_LEFT1           195
#define IDB_FROG_ATTACK_LEFT2           196
#define IDB_FROG_ATTACK_LEFT3           197
#define IDB_FROG_ATTACK_LEFT4           198
#define IDB_FROG_ATTACK_LEFT5           199
#define IDB_FROG_ATTACK_LEFT6           200
#define IDB_BITMAP9                     201
#define IDB_FROG_ATTACK_RIGHT1          201
#define IDB_FROG_ATTACK_RIGHT2          202
#define IDB_FROG_ATTACK_RIGHT3          203
#define IDB_FROG_ATTACK_RIGHT4          204
#define IDB_FROG_ATTACK_RIGHT5          205
#define IDB_FROG_ATTACK_RIGHT6          206
#define IDB_BITMAP2                     207
#define IDB_FROG_DOWN_LEFT              207
#define IDB_HP_0                        208
#define IDB_HP_10                       209
#define IDB_HP_20                       210
#define IDB_HP_30                       211
#define IDB_BITMAP8                     212
#define IDB_HP_40                       212
#define IDB_HP_50                       213
#define IDB_HP_60                       214
#define IDB_HP_70                       215
#define IDB_HP_80                       216
#define IDB_HP_90                       217
#define IDB_HP_100                      218
#define IDB_BITMAP3                     219
#define IDB_GAME_OVER_0                 219
#define IDB_BITMAP4                     220
#define IDB_BITMAP6                     221
#define IDB_BITMAP7                     222
#define IDB_BITMAP10                    223
#define IDB_BITMAP11                    224
#define IDB_BITMAP12                    225
#define IDB_BITMAP13                    226
#define IDB_BITMAP14                    227
#define IDB_BITMAP15                    228
#define IDB_BITMAP16                    229
#define IDB_BITMAP17                    230
#define IDB_BITMAP18                    231
#define IDB_BITMAP19                    232
#define IDB_GAME_OVER_1                 233
#define IDB_GAME_OVER_10                234
#define IDB_GAME_OVER_11                235
#define IDB_GAME_OVER_12                236
#define IDB_GAME_OVER_13                237
#define IDB_GAME_OVER_14                238
#define IDB_GAME_OVER_4                 239
#define IDB_GAME_OVER_3                 240
#define IDB_GAME_OVER_6                 241
#define IDB_GAME_OVER_7                 242
#define IDB_GAME_OVER_9                 243
#define IDB_GAME_OVER_8                 244
#define IDB_GAME_OVER_5                 245
#define IDB_GAME_OVER_2                 246
#define IDB_BITMAP20                    247
#define IDB_MONSTER_ATTACK_LEFT1        248
#define IDB_MONSTER_ATTACK_LEFT2        249
#define IDB_MONSTER_ATTACK_LEFT3        250
#define IDB_MONSTER_ATTACK_RIGHT1       251
#define IDB_MONSTER_ATTACK_RIGHT2       252
#define IDB_BITMAP26                    253
#define IDB_MONSTER_ATTACK_RIGHT3       253
#define IDB_BACKGROUND2                 254
#define IDB_BACKGROUND3                 255
#define IDB_PORTAL_BLUE1                256
#define IDB_PORTAL_BLUE2                257
#define IDB_PORTAL_PURPLE1              258
#define IDB_BITMAP25                    259
#define IDB_PORTAL_PURPLE2              259
#define IDB_SLASH_01                    260
#define IDB_SLASH_02                    261
#define IDB_SLASH_03                    262
#define IDB_SLASH_04                    263
#define IDB_SLASH_05                    264
#define IDB_SLASH_06                    265
#define IDB_SLASH_07                    266
#define IDB_SLASH_08                    267
#define IDB_SLASH_09                    268
#define IDB_SLASH_10                    269
#define IDB_SLASH_11                    270
#define IDB_SLASH_12                    271
#define IDB_BITMAP35                    272
#define IDB_SLASH_13                    272
#define IDB_LV_UP_01                    274
#define IDB_LV_UP_02                    275
#define IDB_LV_UP_03                    276
#define IDB_LV_UP_04                    277
#define IDB_LV_UP_05                    278
#define IDB_LV_UP_06                    279
#define IDB_LV_UP_07                    280
#define IDB_LV_UP_08                    281
#define IDB_LV_UP_09                    282
#define IDB_LV_UP_10                    283
#define IDB_LV_UP_11                    284
#define IDB_LV_UP_12                    285
#define IDB_LV_UP_13                    286
#define IDB_LV_UP_14                    287
#define IDB_LV_UP_15                    288
#define IDB_LV_UP_16                    289
#define IDB_LV_UP_17                    290
#define IDB_LV_UP_18                    291
#define IDB_LV_UP_19                    292
#define IDB_BITMAP43                    293
#define IDB_LV_UP_20                    293
#define IDB_1                           294
#define IDB_2                           295
#define IDB_3                           296
#define IDB_4                           297
#define IDB_5                           298
#define IDB_6                           299
#define IDB_7                           300
#define IDB_8                           301
#define IDB_9                           302
#define IDB_BITMAP21                    303
#define IDB_0                           303
#define IDB_ATK                         304
#define IDB_HP                          305
#define IDB_BITMAP24                    306
#define IDB_LV                          306
#define IDB_GUNER_STAND_LEFT            307
#define IDB_GUNER_ATTACK_LEFT1          308
#define IDB_GUNER_ATTACK_LEFT2          309
#define IDB_GUNER_ATTACK_LEFT3          310
#define IDB_GUNER_STAND_RIGHT           311
#define IDB_GUNER_ATTACK_RIGHT1         312
#define IDB_GUNER_ATTACK_RIGHT2         313
#define IDB_BITMAP32                    314
#define IDB_GUNER_ATTACK_RIGHT3         314
#define IDB_HEAL_CD_0                   315
#define IDB_HEAL_CD_1                   316
#define IDB_HEAL_CD_2                   317
#define IDB_HEAL_CD_3                   318
#define IDB_HEAL_CD_4                   319
#define IDB_HEAL_CD_5                   320
#define IDB_HEAL_CD_6                   321
#define IDB_HEAL_CD_7                   322
#define IDB_SLASH_CD_0                  323
#define IDB_SLASH_CD_1                  324
#define IDB_SLASH_CD_2                  325
#define IDB_SLASH_CD_3                  326
#define IDB_SLASH_CD_4                  327
#define IDB_SLASH_CD_5                  328
#define IDB_SLASH_CD_6                  329
#define IDB_BITMAP42                    330
#define IDB_SLASH_CD_7                  330
#define IDB_HEAL_CD_8                   331
#define IDB_BITMAP23                    332
#define IDB_SLASH_CD_8                  332
#define IDB_BITMAP22                    333
#define IDB_BACKGROUND4                 334
#define IDB_MAGE_STAND_LEFT             335
#define IDB_MAGE_ATTACK_LEFT1           336
#define IDB_MAGE_ATTACK_LEFT2           337
#define IDB_MAGE_ATTACK_LEFT3           338
#define IDB_MAGE_ATTACK_LEFT4           339
#define IDB_MAGE_ATTACK_LEFT5           340
#define IDB_MAGE_ATTACK_LEFT6           341
#define IDB_MAGE_ATTACK_LEFT7           342
#define IDB_MAGE_ATTACK_LEFT8           343
#define IDB_MAGE_STAND_RIGHT            344
#define IDB_MAGE_ATTACK_RIGHT1          345
#define IDB_MAGE_ATTACK_RIGHT2          346
#define IDB_MAGE_ATTACK_RIGHT3          347
#define IDB_MAGE_ATTACK_RIGHT4          348
#define IDB_MAGE_ATTACK_RIGHT5          349
#define IDB_MAGE_ATTACK_RIGHT6          350
#define IDB_MAGE_ATTACK_RIGHT7          351
#define IDB_BITMAP48                    352
#define IDB_MAGE_ATTACK_RIGHT8          352
#define IDB_BITMAP49                    353
#define IDB_POISON_01                   353
#define IDB_BITMAP50                    354
#define IDB_POISON_02                   354
#define IDB_BITMAP51                    355
#define IDB_POISON_03                   355
#define IDB_BITMAP52                    356
#define IDB_POISON_04                   356
#define IDB_BITMAP53                    357
#define IDB_POISON_05                   357
#define IDB_BITMAP54                    358
#define IDB_POISON_06                   358
#define IDB_BITMAP55                    359
#define IDB_POISON_07                   359
#define IDB_BITMAP56                    360
#define IDB_POISON_08                   360
#define IDB_BITMAP57                    361
#define IDB_POISON_09                   361
#define IDB_BITMAP58                    362
#define IDB_POISON_10                   362
#define IDB_BITMAP59                    363
#define IDB_POISON_11                   363
#define IDB_BITMAP60                    364
#define IDB_POISON_12                   364
#define IDB_BITMAP61                    365
#define IDB_POISON_13                   365
#define IDB_BITMAP62                    366
#define IDB_POISON_14                   366
#define IDB_BITMAP63                    367
#define IDB_POISON_15                   367
#define IDB_BITMAP64                    368
#define IDB_POISON_16                   368
#define IDB_BITMAP65                    369
#define IDB_POISON_17                   369
#define IDB_BITMAP66                    370
#define IDB_POISON_18                   370
#define IDB_BITMAP67                    371
#define IDB_POISON_19                   371
#define IDB_BITMAP68                    372
#define IDB_POISON_20                   372
#define IDB_INFO                        374
#define IDB_INFO1                       375
#define IDB_BITMAP29                    376
#define IDB_INFO2                       376
#define IDB_BITMAP27                    377
#define IDB_BOSS_STAND                  377
#define IDB_BOSS_STAND1                 379
#define IDB_BOSS_STAND2                 380
#define IDB_BOSS_STAND3                 381
#define IDB_BOSS_STAND4                 382
#define IDB_BOSS_STAND5                 383
#define IDB_BOSS_STAND6                 384
#define IDB_BOSS_STAND7                 385
#define IDB_BITMAP38                    386
#define IDB_BOSS_STAND8                 386
#define IDB_BITMAP28                    387
#define IDB_BOSS_ICON                   387
#define IDB_HEAL_01                     388
#define IDB_HEAL_02                     389
#define IDB_HEAL_03                     390
#define IDB_HEAL_04                     391
#define IDB_HEAL_05                     392
#define IDB_HEAL_06                     393
#define IDB_HEAL_07                     394
#define IDB_HEAL_08                     395
#define IDB_BITMAP41                    396
#define IDB_HEAL_09                     396
#define IDB_BITMAP30                    397
#define IDB_POISON_ROOT                 397
#define IDB_PNG1                        398
#define IDB_PNG2                        399
#define IDB_PNG3                        400
#define IDB_PNG4                        401
#define IDB_PNG5                        402
#define IDB_PNG6                        403
#define IDB_LASER_07                    404
#define IDB_LASER_08                    405
#define IDB_LASER_09                    406
#define IDB_LASER_10                    407
#define IDB_LASER_11                    408
#define IDB_LASER_12                    409
#define IDB_LASER_13                    410
#define IDB_LASER_14                    411
#define IDB_LASER_15                    412
#define IDB_LASER_16                    413
#define IDB_LASER_01                    414
#define IDB_LASER_02                    415
#define IDB_LASER_03                    416
#define IDB_LASER_04                    417
#define IDB_LASER_05                    418
#define IDB_BITMAP39                    419
#define IDB_LASER_06                    419
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        420
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
